---
# This role conains tasks to deploy the Oracle Management Cloud Agent on Linux x86-64 machines

- name: Check for cloud agent files.
  local_action: stat path={{ role_path }}/files/{{ inventory_hostname }}/cloudagent_linux.x64_{{ omc_agent_version }}.zip
  become: false
  register: ls_omc_cloudagent_image

- name: OMC cloudagent image files missing
  fail:
    msg="omc cloud agent image file missing.  please place cloudagent_linux.x64_{{ omc_agent_version }} in the ./files directory."
  when: ls_omc_cloudagent_image.stat.exists == False
  tags:
    - check
    - install

- name: Installing dependencies
  yum:
    name={{ item }}
    state=present
  with_items: omc_agent_packages
  tags: install

- name: Creating OMC cloudagent group
  group:
    name={{ omc_agent_group }}
    gid={{ omc_agent_gid }}
    state=present
  tags: user

- name: Creating OMC cloudagent user
  user:
    name={{ omc_agent_user }}
    group={{ omc_agent_group }}
    uid={{ omc_agent_uid }}
    state=present
  tags: user


- name: Configure ulimits for OMC user
  pam_limits:
    domain: "{{ omc_agent_user }}"
    limit_type: "{{item.limit_type}}"
    limit_item: "{{item.limit_item}}"
    value: "{{item.value}}"
  with_items:
    - { limit_type: '-', limit_item: 'nofile', value: 400000 }
    - { limit_type: '-', limit_item: 'nproc', value: 400000 }
    - { limit_type: 'soft', limit_item: 'memlock', value: unlimited }
    - { limit_type: 'hard', limit_item: 'memlock', value: unlimited }
  tags: user

- name: Reload settings & limits from configuraltion file
  shell: sysctl --system
  tags: user-ulimits

- name: Check for an existing installation of OMC cloud agent
  stat:
    path: "{{ omc_agent_base_dir }}/agent_inst/bin/omcli"
  register: existing_omc_install

- name: creating base directory
  file:
    path={{ omc_agent_base_dir }}
    state=directory
    owner={{ omc_agent_user }}
    group={{ omc_agent_group }}
  tags: install
  when: existing_omc_install.stat.exists == False

- name: creating temporary directory
  file:
    path=/tmp/ansible_omc_cloudagent
    state=directory
    owner={{ omc_agent_user }}
    group={{ omc_agent_group }}
  tags: install
  when: existing_omc_install.stat.exists == False


- name: uploading omc cloudagent installer
  unarchive: |
    src=files/cloudagent_linux.x64_{{ omc_agent_version }}.zip
    dest=/tmp/ansible_omc_cloudagent
  tags: install
  when: existing_omc_install.stat.exists == False


- name: installing omc cloudagent
  shell: |
    /tmp/ansible_omc_cloudagent/agentInstall.sh \
      TENANT_NAME={{ tenant_name }} \
      AGENT_REGISTRATION_KEY={{ agent_registration_key}} \
      AGENT_BASE_DIRECTORY={{ omc_agent_base }} \
      OMC_URL={{ omc_url }} \
      GATEWAY_HOST={{ gateway_host }} \
      GATEWAY_PORT={{ gateway_port }} \
      ADDITIONAL_GATEWAYS={{ additional_gateways }} \
      REINSTALL={{ agent_reinstall }}
  args:
    chdir: /tmp/ansible_omc_cloudagent
  become: yes
  become_user: "{{ omc_agent_user }}"
  tags: install
  when: existing_omc_install.stat.exists == False


- name: removing omc cloudagent installer
  file:
    path=/tmp/ansible_omc_cloudagent
    state=absent
  tags: install

- name: executing root.sh configuration script
  shell: "{{ omc_agent_base }}/core/{{ omc_agent_version }}/root.sh"
  tags: install
  when: existing_omc_install.stat.exists == False


- name: copy init.d script
  copy:
    src: "{{ files_path }}/{{ omc_agent_init_script }}"
    dest: /etc/init.d/omc-agent
    owner: root
    group: root
    mode: 0744
  tags: install

- name: set script to start at boot
  shell: "chkconfig --add omc-agent && chkconfig --level 2345 omc-agent on"
  become: yes
  become_user: root
  tags: install

- name: setting agent permissions
  shell: "{{ item }}"
  with_items: "{{ omc_agent_permissions }}"
  become: yes
  become_user: root
  tags: permissions