---
# This role conains tasks to deploy the Oracle Management Cloud Agent on Linux x86-64 machines

- name: omc cloudagent image file check
  command: ls files/cloudagent_linux.x64_{{ omc_agent.version }}.zip
  connection: local
  sudo: false
  register: ls_omc_cloudagent_image
  changed_when: false
  tags:
    - check
    - install

- name: omc cloudagent image file missing
  fail:
    msg="omc cloud agent image file missing.  please place cloudagent_linux.x64_{{ omc_agent.version }} in the ./files directory."
  when: ls_omc_cloudagent_image.stdout !=
        "files/cloudagent_linux.x64_{{ omc_agent.version }}.zip"
  tags:
    - check
    - install

- name: installing dependencies
  yum:
    name={{ item }}
    state=present
  with_items: omc_agent.packages
  tags: install

- name: creating omc cloudagent group
  group:
    name={{ omc_agent.group }}
    gid={{ omc_agent.gid }}
    state=present
  tags: user

- name: creating omc cloudagent user
  user:
    name={{ omc_agent.user }}
    group={{ omc_agent.group }}
    uid={{ omc_agent.uid }}
    state=present
  tags: user

- name: configure ulimits
  pam_limits:
    domain: "{{ omc_agent.user }}"
    limit_type: "{{item.limit_type}}"
    limit_item: "{{item.limit_item}}"
    value: "{{item.value}}"
  with_items:
    - { limit_type: '-', limit_item: 'nofile', value: 400000 }
    - { limit_type: '-', limit_item: 'nproc', value: 400000 }
    - { limit_type: 'soft', limit_item: 'memlock', value: unlimited }
    - { limit_type: 'hard', limit_item: 'memlock', value: unlimited }
  tags: user-ulimits

- name: reload settings from all system configuration files
  shell: sysctl --system
  tags: user-ulimits

- name: creating base directory
  file: |
    path={{ omc_agent.base_dir }}
    state=directory
    owner={{ omc_agent.user }}
    group={{ omc_agent.group }}
  tags: install

- name: creating temporary directory
  file: |
    path=/tmp/ansible_omc_cloudagent
    state=directory
    owner={{ omc_agent.user }}
    group={{ omc_agent.group }}
  tags: install

- name: uploading omc cloudagent installer
  unarchive: |
    src=files/cloudagent_linux.x64_{{ omc_agent.version }}.zip
    dest=/tmp/ansible_omc_cloudagent
  tags: install

- name: installing omc cloudagent
  shell: |
    /tmp/ansible_omc_cloudagent/agentInstall.sh \
      TENANT_NAME={{ tenant_name }} \
      AGENT_REGISTRATION_KEY={{ agent_registration_key}} \
      AGENT_BASE_DIRECTORY={{ omc_agent.base }} \
      OMC_URL={{ omc_url }} \
      GATEWAY_HOST={{ gateway_host }} \
      GATEWAY_PORT={{ gateway_port }} \
      ADDITIONAL_GATEWAYS={{ additional_gateways }} \
      REINSTALL={{ agent_reinstall }}
  args:
    chdir: /tmp/ansible_omc_cloudagent
  sudo_user: "{{ omc_agent.user }}"
  tags: install

- name: removing omc cloudagent installer
  file:
    path=/tmp/ansible_omc_cloudagent
    state=absent
  tags: install

- name: executing root.sh configuration script
  shell: "{{ omc_agent.base }}/core/{{ omc_agent.version }}/root.sh"
  tags: install

# - name: copy init.d script
#     tags: post-install
#     copy:
#       src: "{{ files_path }}/{{ omc_agent.init_script }}"
#       dest: /etc/init.d/omc-agent
#       owner: root
#       group: root
#       mode: 0744

#   - name: set script to start at boot
#     shell: "chkconfig --add omc-agent && chkconfig --level 2345 omc-agent on"
#     become: yes
#     become_user: root
#     tags: post-install

- name: set up default permissions for log fetching (/var/log)
  shell: "setfacl -d -m u:{{ omc_agent.user }}:r /var/log"
  become: yes
  become_user: root
  tags: permissions

- name: set up default permissions for log fetching (/var/log/audit)
  shell: "setfacl -d -m u:{{ omc_agent.user }}:r /var/log/audit"
  become: yes
  become_user: root
  tags: permissions

- name: set up permissions for log fetching (/var/log/yum.log*)
  shell: "setfacl -m u:{{ omc_agent.user }}:r /var/log/yum.log*"
  become: yes
  become_user: root
  tags: permissions
- name: set up permissions for log fetching (/var/log/message*)
  shell: "setfacl -m u:{{ omc_agent.user }}:r /var/log/message*"
  become: yes
  become_user: root
  tags: permissions
- name: set up permissions for log fetching (/var/log/audit/audit*)
  shell: "setfacl -m u:{{ omc_agent.user }}:r /var/log/audit/audit*"
  become: yes
  become_user: root
  tags: permissions
- name: set up permissions for log fetching (/var/log/secure*)
  shell: "setfacl -m u:{{ omc_agent.user }}:r /var/log/secure*"
  become: yes
  become_user: root
  tags: permissions
- name: set up permissions for log fetching (/var/log/secure*)
  shell: "setfacl -m u:{{ omc_agent.user }}:r /var/log/maillog*"
  become: yes
  become_user: root
  tags: permissions

- name: set up permissions for log fetching (/var/log/cell*)
  shell: "setfacl -m u:{{ omc_agent.user }}:r /var/log/cell*"
  become: yes
  become_user: root
  tags: permissions
- name: set up permissions for log fetching (/var/log/asmaudit*)
  shell: "setfacl -m u:{{ omc_agent.user }}:r /var/log/asmaudit*"
  become: yes
  become_user: root
  tags: permissions